---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-express-app-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-express-app
  template:
    metadata:
      labels:
        app: my-express-app
    spec:
      containers:
      - name: my-express-app
        image: noyusu/my-express-app:latest
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: my-express-app-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: my-express-app
