name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ steps.packagejson.outputs.app_name }}:latest
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get app name from package.json
        id: packagejson
        run: echo "::set-output name=app_name::$(jq -r .name package.json)"
        shell: bash

      - name: Deploy to Kubernetes via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SCOUTER01_SSH_HOST }}
          username: ${{ secrets.SCOUTER01_SSH_USERNAME }}
          key: ${{ secrets.YUSU_SSH_KEY }}
          port: ${{ secrets.SCOUTER01_SSH_PORT }}
          script: |
            kubectl apply -f ./deployment.yaml
